
package demo.spring.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.junit.Test;

import demo.spring.service_large.HelloWorldws1;
import demo.spring.service_large.HelloWorldws1Service;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-04-07T20:56:46.897+08:00
 * Generated source version: 2.7.15
 * 
 */
public final class HelloWorldws_large {
    private static final QName SERVICE_NAME = new QName("http://service.spring.demo/", "HelloWorldws1Service");

    @Test
    public void testLarge() throws java.lang.Exception {
        URL wsdlURL = HelloWorldws1Service.WSDL_LOCATION;
        
      
        HelloWorldws1Service ss = new HelloWorldws1Service(wsdlURL, SERVICE_NAME);
        HelloWorldws1 port = ss.getHelloWorldws1Port();  
        
        {
        System.out.println("Invoking sayHi299...");
        java.lang.String _sayHi299_arg0 = "";
        java.lang.String _sayHi299__return = port.sayHi299(_sayHi299_arg0);
        System.out.println("sayHi299.result=" + _sayHi299__return);

        }
        
    }

}
