package demo.spring.service_large;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.15
 * 2015-04-07T20:56:47.161+08:00
 * Generated source version: 2.7.15
 * 
 */
@WebServiceClient(name = "HelloWorldws1Service", 
                  wsdlLocation = "HelloWorld1_large.wsdl",
                  targetNamespace = "http://service.spring.demo/") 
public class HelloWorldws1Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.spring.demo/", "HelloWorldws1Service");
    public final static QName HelloWorldws1Port = new QName("http://service.spring.demo/", "HelloWorldws1Port");
    static {
        URL url = HelloWorldws1Service.class.getResource("HelloWorld1_large.wsdl");
        if (url == null) {
            url = HelloWorldws1Service.class.getClassLoader().getResource("HelloWorld1_large.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(HelloWorldws1Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "HelloWorld1_large.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public HelloWorldws1Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldws1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldws1Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldws1Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldws1Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldws1Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HelloWorldws1
     */
    @WebEndpoint(name = "HelloWorldws1Port")
    public HelloWorldws1 getHelloWorldws1Port() {
        return super.getPort(HelloWorldws1Port, HelloWorldws1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldws1
     */
    @WebEndpoint(name = "HelloWorldws1Port")
    public HelloWorldws1 getHelloWorldws1Port(WebServiceFeature... features) {
        return super.getPort(HelloWorldws1Port, HelloWorldws1.class, features);
    }

}
