package demo.spring.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-04-04T14:34:37.123+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://service.spring.demo/", name = "HelloWorldws")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldws {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.spring.demo/", className = "demo.spring.service.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.spring.demo/", className = "demo.spring.service.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayPerson", targetNamespace = "http://service.spring.demo/", className = "demo.spring.service.SayPerson")
    @WebMethod
    @ResponseWrapper(localName = "sayPersonResponse", targetNamespace = "http://service.spring.demo/", className = "demo.spring.service.SayPersonResponse")
    public demo.spring.service.PersonDto sayPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        demo.spring.service.PersonDto arg0
    );
}
