package demo.spring.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-04-04T14:34:37.131+08:00
 * Generated source version: 2.7.11
 * 
 */
@WebServiceClient(name = "HelloWorldwsImplService", 
                  wsdlLocation = "file:/home/yhjhoo/workspace_play/testWebservice/src/main/resources/HelloWorld.wsdl",
                  targetNamespace = "http://service.spring.demo/") 
public class HelloWorldwsImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.spring.demo/", "HelloWorldwsImplService");
    public final static QName HelloWorldwsImplPort = new QName("http://service.spring.demo/", "HelloWorldwsImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/yhjhoo/workspace_play/testWebservice/src/main/resources/HelloWorld.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldwsImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/yhjhoo/workspace_play/testWebservice/src/main/resources/HelloWorld.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldwsImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldwsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldwsImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldwsImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldwsImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HelloWorldwsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HelloWorldws
     */
    @WebEndpoint(name = "HelloWorldwsImplPort")
    public HelloWorldws getHelloWorldwsImplPort() {
        return super.getPort(HelloWorldwsImplPort, HelloWorldws.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldws
     */
    @WebEndpoint(name = "HelloWorldwsImplPort")
    public HelloWorldws getHelloWorldwsImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldwsImplPort, HelloWorldws.class, features);
    }

}
